// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/share/:token": {
    params: {
      "token": string;
    };
  };
  "/invite/:token": {
    params: {
      "token": string;
    };
  };
  "/onboarding": {
    params: {};
  };
  "/:workspace": {
    params: {
      "workspace": string;
    };
  };
  "/:workspace/issues": {
    params: {
      "workspace": string;
    };
  };
  "/:workspace/issues/:issueId": {
    params: {
      "workspace": string;
      "issueId": string;
    };
  };
  "/:workspace/notes": {
    params: {
      "workspace": string;
    };
  };
  "/:workspace/notes/:noteSlug": {
    params: {
      "workspace": string;
      "noteSlug": string;
    };
  };
  "/:workspace/cycles": {
    params: {
      "workspace": string;
    };
  };
  "/:workspace/cycles/:cycleId": {
    params: {
      "workspace": string;
      "cycleId": string;
    };
  };
  "/:workspace/analytics": {
    params: {
      "workspace": string;
    };
  };
  "/:workspace/settings": {
    params: {
      "workspace": string;
    };
  };
  "/:workspace/inbox": {
    params: {
      "workspace": string;
    };
  };
  "/:workspace/team": {
    params: {
      "workspace": string;
    };
  };
  "/:workspace/databases": {
    params: {
      "workspace": string;
    };
  };
  "/:workspace/databases/:databaseId": {
    params: {
      "workspace": string;
      "databaseId": string;
    };
  };
  "/:workspace/initiatives": {
    params: {
      "workspace": string;
    };
  };
  "/:workspace/projects": {
    params: {
      "workspace": string;
    };
  };
  "/:workspace/projects/:projectId": {
    params: {
      "workspace": string;
      "projectId": string;
    };
  };
  "/:workspace/roadmap": {
    params: {
      "workspace": string;
    };
  };
  "/:workspace/triage": {
    params: {
      "workspace": string;
    };
  };
  "/:workspace/my-issues": {
    params: {
      "workspace": string;
    };
  };
  "/:workspace/git-integration": {
    params: {
      "workspace": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/share/:token" | "/invite/:token" | "/onboarding" | "/:workspace" | "/:workspace/issues" | "/:workspace/issues/:issueId" | "/:workspace/notes" | "/:workspace/notes/:noteSlug" | "/:workspace/cycles" | "/:workspace/cycles/:cycleId" | "/:workspace/analytics" | "/:workspace/settings" | "/:workspace/inbox" | "/:workspace/team" | "/:workspace/databases" | "/:workspace/databases/:databaseId" | "/:workspace/initiatives" | "/:workspace/projects" | "/:workspace/projects/:projectId" | "/:workspace/roadmap" | "/:workspace/triage" | "/:workspace/my-issues" | "/:workspace/git-integration";
  };
  "../routes/index.tsx": {
    id: "../routes/index";
    page: "/";
  };
  "../routes/login.tsx": {
    id: "../routes/login";
    page: "/login";
  };
  "../routes/signup.tsx": {
    id: "../routes/signup";
    page: "/signup";
  };
  "../routes/share.$token.tsx": {
    id: "../routes/share.$token";
    page: "/share/:token";
  };
  "../routes/invite.$token.tsx": {
    id: "../routes/invite.$token";
    page: "/invite/:token";
  };
  "../routes/onboarding.tsx": {
    id: "../routes/onboarding";
    page: "/onboarding";
  };
  "../routes/$workspace/layout.tsx": {
    id: "../routes/$workspace/layout";
    page: "/:workspace" | "/:workspace/issues" | "/:workspace/issues/:issueId" | "/:workspace/notes" | "/:workspace/notes/:noteSlug" | "/:workspace/cycles" | "/:workspace/cycles/:cycleId" | "/:workspace/analytics" | "/:workspace/settings" | "/:workspace/inbox" | "/:workspace/team" | "/:workspace/databases" | "/:workspace/databases/:databaseId" | "/:workspace/initiatives" | "/:workspace/projects" | "/:workspace/projects/:projectId" | "/:workspace/roadmap" | "/:workspace/triage" | "/:workspace/my-issues" | "/:workspace/git-integration";
  };
  "../routes/$workspace/index.tsx": {
    id: "../routes/$workspace/index";
    page: "/:workspace";
  };
  "../routes/$workspace/issues.tsx": {
    id: "../routes/$workspace/issues";
    page: "/:workspace/issues";
  };
  "../routes/$workspace/issues.$issueId.tsx": {
    id: "../routes/$workspace/issues.$issueId";
    page: "/:workspace/issues/:issueId";
  };
  "../routes/$workspace/notes.tsx": {
    id: "../routes/$workspace/notes";
    page: "/:workspace/notes";
  };
  "../routes/$workspace/notes.$noteSlug.tsx": {
    id: "../routes/$workspace/notes.$noteSlug";
    page: "/:workspace/notes/:noteSlug";
  };
  "../routes/$workspace/cycles.tsx": {
    id: "../routes/$workspace/cycles";
    page: "/:workspace/cycles";
  };
  "../routes/$workspace/cycles.$cycleId.tsx": {
    id: "../routes/$workspace/cycles.$cycleId";
    page: "/:workspace/cycles/:cycleId";
  };
  "../routes/$workspace/analytics.tsx": {
    id: "../routes/$workspace/analytics";
    page: "/:workspace/analytics";
  };
  "../routes/$workspace/settings.tsx": {
    id: "../routes/$workspace/settings";
    page: "/:workspace/settings";
  };
  "../routes/$workspace/inbox.tsx": {
    id: "../routes/$workspace/inbox";
    page: "/:workspace/inbox";
  };
  "../routes/$workspace/team.tsx": {
    id: "../routes/$workspace/team";
    page: "/:workspace/team";
  };
  "../routes/$workspace/databases.tsx": {
    id: "../routes/$workspace/databases";
    page: "/:workspace/databases";
  };
  "../routes/$workspace/databases.$databaseId.tsx": {
    id: "../routes/$workspace/databases.$databaseId";
    page: "/:workspace/databases/:databaseId";
  };
  "../routes/$workspace/initiatives.tsx": {
    id: "../routes/$workspace/initiatives";
    page: "/:workspace/initiatives";
  };
  "../routes/$workspace/projects.tsx": {
    id: "../routes/$workspace/projects";
    page: "/:workspace/projects";
  };
  "../routes/$workspace/projects.$projectId.tsx": {
    id: "../routes/$workspace/projects.$projectId";
    page: "/:workspace/projects/:projectId";
  };
  "../routes/$workspace/roadmap.tsx": {
    id: "../routes/$workspace/roadmap";
    page: "/:workspace/roadmap";
  };
  "../routes/$workspace/triage.tsx": {
    id: "../routes/$workspace/triage";
    page: "/:workspace/triage";
  };
  "../routes/$workspace/my-issues.tsx": {
    id: "../routes/$workspace/my-issues";
    page: "/:workspace/my-issues";
  };
  "../routes/$workspace/git-integration.tsx": {
    id: "../routes/$workspace/git-integration";
    page: "/:workspace/git-integration";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "../routes/index": unknown;
  "../routes/login": unknown;
  "../routes/signup": unknown;
  "../routes/share.$token": unknown;
  "../routes/invite.$token": unknown;
  "../routes/onboarding": unknown;
  "../routes/$workspace/layout": unknown;
  "../routes/$workspace/index": unknown;
  "../routes/$workspace/issues": unknown;
  "../routes/$workspace/issues.$issueId": unknown;
  "../routes/$workspace/notes": unknown;
  "../routes/$workspace/notes.$noteSlug": unknown;
  "../routes/$workspace/cycles": unknown;
  "../routes/$workspace/cycles.$cycleId": unknown;
  "../routes/$workspace/analytics": unknown;
  "../routes/$workspace/settings": unknown;
  "../routes/$workspace/inbox": unknown;
  "../routes/$workspace/team": unknown;
  "../routes/$workspace/databases": unknown;
  "../routes/$workspace/databases.$databaseId": unknown;
  "../routes/$workspace/initiatives": unknown;
  "../routes/$workspace/projects": unknown;
  "../routes/$workspace/projects.$projectId": unknown;
  "../routes/$workspace/roadmap": unknown;
  "../routes/$workspace/triage": unknown;
  "../routes/$workspace/my-issues": unknown;
  "../routes/$workspace/git-integration": unknown;
};